package by.com.lifetech.billingapi.wsdl.message;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-03-05T17:49:13.004+03:00
 * Generated source version: 4.1.0
 *
 */
@WebService(targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", name = "MessageTransmissionAPI")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageTransmissionAPI {

    @WebMethod
    @Action(input = "http://api.ws.rtn.idr.astelit.ukr/MessageTransmissionAPI/transmitMessageRequest", output = "http://api.ws.rtn.idr.astelit.ukr/MessageTransmissionAPI/transmitMessageResponse")
    @RequestWrapper(localName = "transmitMessage", targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.message.TransmitMessage")
    @ResponseWrapper(localName = "transmitMessageResponse", targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.message.TransmitMessageResponse")
    @WebResult(name = "result", targetNamespace = "")
    public by.com.lifetech.billingapi.wsdl.message.GeneralResult transmitMessage(

        @WebParam(name = "message", targetNamespace = "")
        by.com.lifetech.billingapi.wsdl.message.Message message
    );

    @WebMethod
    @Action(input = "http://api.ws.rtn.idr.astelit.ukr/MessageTransmissionAPI/transmitBulkMessageRequest", output = "http://api.ws.rtn.idr.astelit.ukr/MessageTransmissionAPI/transmitBulkMessageResponse")
    @RequestWrapper(localName = "transmitBulkMessage", targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.message.TransmitBulkMessage")
    @ResponseWrapper(localName = "transmitBulkMessageResponse", targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.message.TransmitBulkMessageResponse")
    @WebResult(name = "result", targetNamespace = "")
    public by.com.lifetech.billingapi.wsdl.message.GeneralResult transmitBulkMessage(

        @WebParam(name = "bulkMessage", targetNamespace = "")
        by.com.lifetech.billingapi.wsdl.message.BulkMessage bulkMessage
    );

    @WebMethod
    @Action(input = "http://api.ws.rtn.idr.astelit.ukr/MessageTransmissionAPI/getAllMessagesRequest", output = "http://api.ws.rtn.idr.astelit.ukr/MessageTransmissionAPI/getAllMessagesResponse")
    @RequestWrapper(localName = "getAllMessages", targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.message.GetAllMessages")
    @ResponseWrapper(localName = "getAllMessagesResponse", targetNamespace = "http://api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.message.GetAllMessagesResponse")
    @WebResult(name = "result", targetNamespace = "")
    public by.com.lifetech.billingapi.wsdl.message.GetAllMessagesResult getAllMessages()
;
}
