package by.com.lifetech.billingapi.models.enums;

import by.com.lifetech.billingapi.exceptions.BusinessException;

public enum DictName {
	
	DICT_STATE("DICT_STATE"), 
	DICT_SEGMENT("DICT_SEGMENT"), 
	DICT_RISK_LEVEL("DICT_RISK_LEVEL"), 
	DICT_CONTRACT_TYPE("DICT_CONTRACT_TYPE"), 
	DICT_LINE_LEVEL("DICT_LINE_LEVEL"), 
	DICT_TH_TYPE("DICT_TH_TYPE"), 
	DICT_TARIFF("DICT_TARIFF"), 
	DICT_CATEGORY("DICT_CATEGORY"), 
	DICT_REG_TYPE("DICT_REG_TYPE"),
	DICT_PCRF_ATTR("DICT_PCRF_ATTR"),
	DICT_HSS_ATTR("DICT_HSS_ATTR"),
	DICT_SERVICE_NAME("DICT_SERVICE_NAME"),
	DICT_SERVICE_SUBGROUP("DICT_SERVICE_SUBGROUP"),
	DICT_SERVICE_GROUP("DICT_SERVICE_GROUP"),
	DICT_CHARGE_EVENT_GROUP("DICT_CHARGE_EVENT_GROUP"),
	DICT_ERROR_CODE("DICT_ERROR_CODE"),
	DICT_BANKS("DICT_BANKS"),
	DICT_MP_FIN_OPERATION("DICT_MP_FIN_OPERATION"),
	DICT_MC_FIN_OP_IND("DICT_MC_FIN_OP_IND"),
	DICT_MC_FIN_OP_CORP("DICT_MC_FIN_OP_CORP"),
	DICT_SUBS_TERM_TYPE("DICT_SUBS_TERM_TYPE"),
	DICT_REFUND_MONEY_REASON("DICT_REFUND_MONEY_REASON"),
	DICT_SIM_CHANGE("DICT_SIM_CHANGE"),
	DICT_SIM_CHANGE_DEALER("DICT_SIM_CHANGE_DEALER"),
	DICT_OCCUPATION("DICT_OCCUPATION"),
	DICT_INFORMATION_SOURCE("DICT_INFORMATION_SOURCE"),
	DICT_PASSPORT_TYPE("DICT_PASSPORT_TYPE"),
	DICT_ADR_COUNTRY("DICT_ADR_COUNTRY"),
	DICT_ADR_CITY("DICT_ADR_CITY"),
	DICT_ADR_CITY_TYPE("DICT_ADR_CITY_TYPE"),
	DICT_ADR_DISTRICT("DICT_ADR_DISTRICT"),
	DICT_ADR_REGION("DICT_ADR_REGION"),
	DICT_ADR_STREET_TYPE("DICT_ADR_STREET_TYPE"),
	DICT_ADR_TYPE("DICT_ADR_TYPE"),
	DICT_NUMBER_SELECTION("DICT_NUMBER_SELECTION");

	private final String dictCode;

	DictName(String dictCode) {
		this.dictCode = dictCode;
	}

	public String toString() {
		return this.dictCode;
	}

	public static DictName getByValue(String v) throws BusinessException {
		for (DictName s : values()) {
			if (s.toString().equals(v.toUpperCase()))
				return s;
		}
		throw new BusinessException(BusinessErrorCode.ENTITY_NOT_FOUND.name(), "Dictionary type " + v + " not found");
	}
}
