
package by.com.lifetech.billingapi.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ChainAPI", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChainAPI {


    /**
     * 
     * @return
     *     returns by.com.lifetech.billingapi.wsdl.ChainsListResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredChainsNames", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.GetRegisteredChainsNames")
    @ResponseWrapper(localName = "getRegisteredChainsNamesResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.GetRegisteredChainsNamesResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getRegisteredChainsNamesRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getRegisteredChainsNamesResponse")
    public ChainsListResult getRegisteredChainsNames();

    /**
     * 
     * @param chainName
     * @return
     *     returns by.com.lifetech.billingapi.wsdl.ChainSignatureResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChainSignature", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.GetChainSignature")
    @ResponseWrapper(localName = "getChainSignatureResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.GetChainSignatureResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getChainSignatureRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getChainSignatureResponse")
    public ChainSignatureResult getChainSignature(
        @WebParam(name = "chainName", targetNamespace = "")
        String chainName);

    /**
     * 
     * @param chainRequest
     * @return
     *     returns by.com.lifetech.billingapi.wsdl.ChainResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeChain", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.ExecuteChain")
    @ResponseWrapper(localName = "executeChainResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.ExecuteChainResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeChainRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeChainResponse")
    public ChainResult executeChain(
        @WebParam(name = "chainRequest", targetNamespace = "")
        ChainRequest chainRequest);

    /**
     * 
     * @param chainRequest
     * @return
     *     returns by.com.lifetech.billingapi.wsdl.ChainResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeDebugChain", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.ExecuteDebugChain")
    @ResponseWrapper(localName = "executeDebugChainResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "by.com.lifetech.billingapi.wsdl.ExecuteDebugChainResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeDebugChainRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeDebugChainResponse")
    public ChainResult executeDebugChain(
        @WebParam(name = "chainRequest", targetNamespace = "")
        ChainRequest chainRequest);

}
